### ISSUE TITLE
Invalid character when parsing Events

### ISSUE THREAD

**Issue by adomenech73** [rjz/githubhook#12]
I'm trying to parse push Events from git web hooks, I'm following what documentation and examples show about using github.com/google/go-github structs, so my code would be something like:

```Golang
const secret = "supersecret"
.....
hook, err := githubhook.Parse([]byte(secret), r)
if err != nil {
	log.Printf("Failed processing hook! ('%s')", err)
	return
}
fmt.Println("Received Event", hook.Event)
if hook.Event == "push" {
	evt := github.PushEvent{}
	if err := json.Unmarshal(hook.Payload, &evt); err != nil {
		log.Println("Error: ", err)
		if e, ok := err.(*json.SyntaxError); ok {
			log.Printf("syntax error at byte offset %d", e.Offset)
		}
	}
	fmt.Println(evt.Repo)
	fmt.Println(evt.Compare)
}
```

And I always receive this error:

```Bash
Received Event push
2017/12/04 10:48:13 Error:  invalid character 'p' looking for beginning of value
2017/12/04 10:48:13 syntax error at byte offset 1
2017/12/04 10:48:13 [POST] "/alerts" 466.314µs
```
What I've seen is that 'p' corresponds to payload as first element of the json that contains all the rest. something like ```map[payload:[{... payload content...}]]```

**Comment by rjz** [comment]
Hey @adomenech73, and thanks for reporting! Sanity check before trying to create a test case: could you confirm that your webhook is [configured to send json](https://developer.github.com/webhooks/creating/#content-type)?

If it is, could you provide an example value of the `hook.Payload` JSON that leads up to the error?

**Comment by adomenech73** [comment]
@rjz My absolute fault, you are right I didn't change my webhook from default type, so it was application/x-www-form-urlencoded. I changed to json and now works as expected, sorry for that and Thanks a lot

**Comment by rjz** [comment]
No worries! Please circle back if you run into any other issues!
