### ISSUE TITLE
support the sha256 signature (as the sha1 has been deprecated)

### ISSUE THREAD

**Issue by dolanor** [rjz/githubhook#13]
Hi,
Thank you for this library. Using it lately, I discovered it still uses the default deprecated signature hash function.
[It is deprecated since](https://docs.github.com/en/webhooks-and-events/webhooks/securing-your-webhooks#validating-payloads-from-github)

> Note: For backward-compatibility, we also include the x-hub-signature header that is generated using the SHA-1 hash function. If possible, we recommend that you use the x-hub-signature-256 header for improved security. The example below demonstrates using the x-hub-signature-256 header.

**Comment by rjz** [comment]
Thanks, @dolanor, this should be fixed in #15.

Please reopen if you run into any issues with the updated signature!
